### ISSUE TITLE
Any other animation ideas?

### ISSUE THREAD

**Issue by vGsteiger** [vGsteiger/caos_gruppe_144#14]
Leave a comment with ideas so we can collect some ideas.

So far I have:

- [x] GOL
- [x] Firework
- [x] Letters
- [x] Weather animations
- [ ] Waves

Do you have any other ideas?

**Comment by zGatsu** [comment]
Here some more ideas:

- Time
- Stars (which go from left to right)
- Random Pattern (randomly lighting up LED's with random Color. Might look ugly :-) )
- Temperature

**Comment by vGsteiger** [comment]
@joeyzgraggen You can just make a tick off list, so we can easily keep track :).

And the temperature is already implemented in the weather "animations". 

What do you mean by stars?

Thanks for the great feedback!

**Comment by zGatsu** [comment]
That's great that the temperature is already implemented. I didn't see it when i looked over the code.

I think i am going to explain the "stars" effect in our next meeting.

**Comment by vGsteiger** [comment]
@joeyzgraggen still, if you change your bullet points to a tick-off list it would make it easier to keep track of what is already done ;-)
